### GENERAL SETTINGS ###

# Site settings
title: CHENNAI MAKERSPACE
description: "Chennai's first makerspace"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://chennaimakerspace.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url: https://www.facebook.com/Chennaimakers/
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 8/15, Jeevan Surabhi,
    - Judge Colony, 2nd street, Tambaram Sanitorium
    - Chennai - 47.
email: makeinchennai@gmail.com
tel: +91 8754786026


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Saipraveen Durairaman
    position: Founder
    text: Hardware hacker.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:saipraveendurairaman@gmail.com
      - title: twitter
        url: http://twitter.com/dsaipraveen
  - name: Vijayenthiran
    position: Founder, Marketing Head
    text: Chick magnet & Client magnet
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Vijay@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Sibi 
    position: Co-Founder, Operations Head
    text: If this is still running its because of me
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sibi@domain.com
      - title: twitter
        url: http://twitter.com/sibi
  - name: Mervin JB
    position: Co-Founder, Technical Lead
    text: Resistors to Mosfets
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:mervin@domain.com
      - title: twitter
        url: http://twitter.com/mervin
  - name: Adhithya
    position: Co-Founder, Project mentor
    text: IOT champ
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:adithay@domain.com
      - title: twitter
        url: http://twitter.com/Adhithya
  - name: Sanjay
    position: Co-Founder, Project mentor
    text: All rounder
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sanjay@domain.com
      - title: twitter
        url: http://twitter.com/sanjay
  - name: Karthick Singaram
    position: Co-Founder, Project mentor
    text: Anything on startups
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:karthi@domain.com
      - title: twitter
        url: http://twitter.com/karthi



    
# Clients information. Shown on Home and About pages.
clients:
  - name: Deltatec
    img: client01.png
  - name: SSN COllege of Engineering
    img: client02.png
  - name: Public
    img: client03.png
  - name: Public
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Spreading the spirit of making"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Spreading the spirit of making"
    author: Sai.
    position: Dummy